modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="astra"
version="1.0.0"
displayName="Astra"
authors="JSS"
description='''
A.S.T.R.A
'''

[[dependencies.astra]]
modId="forge"
mandatory=true
versionRange="[47,)"
side="BOTH"

[[dependencies.astra]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1]"
side="BOTH"